baseURL: https://taxel-portfolio.netlify.app/
languageCode: en-us
title: Axel Tagnon's Portfolio Wbesite
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Axel and I am an MFA2022 student at London Business School
  blog: {}
  contact:
    address:
      - city: London, #ST 00000
        country: United Kingdom
        #street: Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: atagnon.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7507 388679
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Axel Tagnon
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
     # - icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/axeltagnon/
      - icon: fa-github
        label: GitHub
        url: https://github.com/axel-tagnon/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/axel-tagnon/
  image: ''
  name: Axel Tagnon
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: ThinkatLBS.jpg
        subtitle: A conversation between Tabria Lenard MBA2021 and Axel Tagnon MFA2022 on where progress has been made and where there’s more to be done
        title: Taking stock and looking forward, Black in business in 2021
        url: https://www.london.edu/think/taking-stock-and-looking-forward?utm_source=LinkedIn&utm_medium=sm_channels&utm_campaign=lbsr_BHM21_TL_AT&sc_camp=F2FB8AFA24F54014959D5B136C2F96C1
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
