---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2021-10-21"
description: Data Analytics Project 3 # the title that will show up once someone gets to this page
draft: false

keywords: ""
slug: proj3 # slug is the shorthand URL address... no spaces plz
title: Data Analytics Project 3

author: "Group 11: Guido Bassi - 3542918 
                   Liam Cheung - 3789271
                   Mengyu Liu - 3753296
                   Nohad Mortada - 3689277
                   Jiaye Bai - 3808878
                   Axel Tagnon - 3709761
                   Qingran Zhang 3730453"
                   

output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

<script src="homework3_G11_v3 (1)_files/header-attrs/header-attrs.js"></script>


<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1~
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema~
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, ~
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;~
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa~
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1~
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, ~
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not ~
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not~
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, ~
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,~
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, ~
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;~</code></pre>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table>
<caption>(#tab:eda_on_weight)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<pre class="r"><code>favstats(~weight, data=yrbss)</code></pre>
<pre><code>##   min   Q1 median   Q3 max mean   sd     n missing
##  29.9 56.2   64.4 76.2 181 67.9 16.9 12579    1004</code></pre>
<p><em>There are 1004 missing weights. The average weight is 67.9</em></p>
<pre class="r"><code>ggplot(yrbss, aes (x = weight)) +
  geom_boxplot() +
  theme_minimal() +
  NULL</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-2-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(yrbss, aes (x = weight)) +
  geom_density(alpha = 0.3) +
  theme_minimal() +
  NULL</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-2-2.png" width="648" style="display: block; margin: auto;" /></p>
<p><em>Most weight values are reasonable, between 60 and 75. however, there are some outliers, with some children weighting more than 100 and even more than 150</em></p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<pre class="r"><code>#we first drop all missing values in the dataset
yrbss &lt;- na.omit(yrbss)
#we try to see if there is a correlation between weight and physical activity
yrbss %&gt;%
  select(physically_active_7d, weight) %&gt;%
  cor()</code></pre>
<pre><code>##                      physically_active_7d weight
## physically_active_7d               1.0000 0.0403
## weight                             0.0403 1.0000</code></pre>
<p><em>Surprisingly enough, there is no negative correlation. We would’ve expected that the more the physical activity increases, the more weight decreases</em></p>
<pre class="r"><code>weight_by_activity &lt;- yrbss %&gt;%
  group_by(physically_active_7d) %&gt;%
  summarise(meanweight = mean(weight))
weight_by_activity</code></pre>
<pre><code>## # A tibble: 8 x 2
##   physically_active_7d meanweight
##                  &lt;int&gt;      &lt;dbl&gt;
## 1                    0       67.1
## 2                    1       66.3
## 3                    2       67.8
## 4                    3       68.8
## 5                    4       68.5
## 6                    5       68.3
## 7                    6       68.4
## 8                    7       69.0</code></pre>
<p><em>Indeed, the average eight tends to increase as the level of physical activity increases</em></p>
<pre class="r"><code>plot2 &lt;- ggplot(yrbss, aes(x = weight , y = physically_active_7d)) +
  geom_point() + geom_smooth(method = &quot;lm&quot;)
plot2</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># We then plot height vs weight using the level of physical activity as categorical variable
ggplot(yrbss, aes(x = weight, y = height, colour = physically_active_7d)) +
  geom_point() +
  theme_bw() +
  labs(y = &quot;height&quot;,
       x = &quot;weight&quot;,
       title = &quot;Level of activity&quot;)</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-5-2.png" width="648" style="display: block; margin: auto;" /></p>
<p><em>Surprisingly enough, the correlation in the first graph seems positive. Although it is counter intuitive, high weights don’t necessarily mean high body fat percentage. Maybe, those who are more physically active have lower body fat but more muscles and therefore weigh more?. Even by considering the height in the second graph, so by “adjusting for the body fat”, it’s not always the case that short people that have high weight are less physical active. However, we tend to see mainly dark data points in the bottom right of the graph. Similarly, if you are tall with a low weight you tend to practice quite a lot. It would be interesting to overlap the body mass index to really see if there is a correlation between overweight people and lower physical activity.</em></p>
<p>Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days. RUse the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;%
  mutate(physical_3plus = case_when(physically_active_7d &gt; 2 ~ &quot;yes&quot;,
                                    physically_active_7d &lt; 2 ~ &quot;no&quot;,))

yrbss %&gt;%
  count(physical_3plus) %&gt;%
  mutate(proportions = n / sum(n))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   physical_3plus     n proportions
##   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;
## 1 no              1885      0.226 
## 2 yes             5695      0.682 
## 3 &lt;NA&gt;             771      0.0923</code></pre>
<pre class="r"><code>yrbss %&gt;%
  group_by(physical_3plus) %&gt;%
  summarise(n = n()) %&gt;%
  mutate(proportions = n / sum(n))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   physical_3plus     n proportions
##   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;
## 1 no              1885      0.226 
## 2 yes             5695      0.682 
## 3 &lt;NA&gt;             771      0.0923</code></pre>
<p><em>We get the same results using both functions</em> Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>prop.test(1885,7580)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  1885 out of 7580
## X-squared = 1914, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.239 0.259
## sample estimates:
##     p 
## 0.249</code></pre>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code>ggplot(yrbss, aes (x = weight, y = physical_3plus)) +
  geom_boxplot() +
  theme_minimal() +
  NULL</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><em>As seen before, there is s slight positvie relation between weight and physical activity. We didnt expect this as it is intuitive to say that the most one is physically active the less he/she weights.</em> ## Confidence Interval</p>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>yrbss %&gt;%
  group_by(physical_3plus) %&gt;%
  summarise(n = n(),
            mean_weight = mean(weight, na.rm = TRUE)) %&gt;%
  mutate(
    se = sd(mean_weight, na.rm = TRUE) / sqrt(n),
    lower = mean_weight - 1.96 * se,
    upper = mean_weight + 1.96 * se
  )</code></pre>
<pre><code>## # A tibble: 3 x 6
##   physical_3plus     n mean_weight     se lower upper
##   &lt;chr&gt;          &lt;int&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 no              1885        66.9 0.0207  66.8  66.9
## 2 yes             5695        68.7 0.0119  68.7  68.7
## 3 &lt;NA&gt;             771        67.8 0.0324  67.7  67.9</code></pre>
<pre class="r"><code>mosaic::t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -4, df = 2963, p-value = 1e-04
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.724 -0.871
## sample estimates:
##  mean in group no mean in group yes 
##              66.9              68.7</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -4, df = 2963, p-value = 1e-04
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.724 -0.871
## sample estimates:
##  mean in group no mean in group yes 
##              66.9              68.7</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-7-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.8?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-8-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/directors.png" width="100%" style="display: block; margin: auto;" /></p>
<p>First, I would like you to reproduce this graph. You may find <code>geom_errorbar()</code> and <code>geom_rect()</code> useful.</p>
<pre class="r"><code># creat dateframe containing confidence intervals data for two directors
director &lt;- c(&#39;Tim Burton&#39;,&#39;Steven Spielberg&#39;)
meanrating &lt;- c(6.93,7.57)
lower&lt;- c(6.53,7.27)
upper&lt;- c(7.33,7.87)

df_CIrating&lt;- data.frame(director,meanrating,lower,upper)

# reproduce confidence intervals plot 
ggplot(df_CIrating,aes(x=meanrating,y=factor(director,level = c(&#39;Tim Burton&#39;,&#39;Steven Spielberg&#39;)),color=director))+
  geom_linerange(aes(xmin = lower, xmax = upper),width = 2)+
  geom_pointrange(aes(xmin = lower, xmax = upper),size = 1)+
  geom_errorbar(aes(xmin = lower, xmax = upper),size=2,width = 0.05)+
  geom_text(aes(label=meanrating),hjust=0.5, vjust=-1,color=&quot;black&quot;,size=8,face=&quot;bold&quot;)+
  geom_text(aes(label=lower,x=lower),hjust=0.5, vjust=-1,color=&quot;black&quot;,size=5)+
  geom_text(aes(label=upper,x=upper),hjust=0.5, vjust=-1,color=&quot;black&quot;,size=5)+
  theme_bw() + #delete background
  xlab(&quot;Mean IMDB Rating&quot;) +
  labs(title = &quot;Do Spielbarg and Burton have the same IMDB ratings?&quot;, 
       subtitle = &quot;95% confidence intervals overlap&quot;) +
  theme(legend.position = &quot;none&quot;,
        axis.title.y = element_blank(),
        axis.title.x = element_text(face = &quot;bold&quot;),
        plot.title = element_text(face = &quot;bold&quot;),
        plot.subtitle = element_text(face = &quot;bold&quot;))+
  geom_rect(color= &quot;grey&quot;,fill = &quot;grey&quot;, alpha = 0.5, 
    mapping = aes_string(x = &quot;meanrating&quot;, y = &quot;director&quot;), 
    xmin = 7.27,
    xmax = 7.33,
    ymin = -Inf,
    ymax = Inf)</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-9-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>In addition, you will run a hpothesis test. You should use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<blockquote>
<p>Before anything, write down the null and alternative hypotheses, as well as the resulting test statistic and the associated t-stat or p-value. At the end of the day, what do you conclude?</p>
</blockquote>
<p><strong>Null hypotheses: The difference in mean IMDB ratings between Spielbarg and Burton is equal to zero</strong> <strong>Alternate hypotheses: The difference in mean IMDB ratings between Spielbarg and Burton is not equal to zero</strong> <strong>Test statistic for this hypotheses test should be the difference in sample means of ratings for two directors minus the term (μ1-μ2) which is equal to zero in this situation, divided by the standard deviation of the difference between the two sample means</strong> <strong>The associated t-stat = 2.70</strong> <strong>Since the t-stat 2.70 is much greater than 2, we reject the null hypotheses. In conclusion, the mean difference between two directors’ movie ratings is really different from zero and therefore there is a significant difference in IMDB rating for them</strong></p>
<p>You can load the data and examine its structure</p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Avenge~
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;~
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevorrow~
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015, 20~
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93, 1~
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+08, ~
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+08, ~
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, 920~
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658, 9~
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752, 35~
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7.2, ~</code></pre>
<pre class="r"><code>skimr::skim(movies)</code></pre>
<table>
<caption><span id="tab:load-movies-data">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">movies</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">2961</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">title</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">83</td>
<td align="right">0</td>
<td align="right">2907</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">genre</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">17</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">director</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">32</td>
<td align="right">0</td>
<td align="right">1366</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="13%" />
<col width="6%" />
<col width="9%" />
<col width="6%" />
<col width="6%" />
<col width="4%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="28%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2.00e+03</td>
<td align="right">9.95e+00</td>
<td align="right">1920.0</td>
<td align="right">2.00e+03</td>
<td align="right">2.00e+03</td>
<td align="right">2.01e+03</td>
<td align="right">2.02e+03</td>
<td align="left">▁▁▁▂▇</td>
</tr>
<tr class="even">
<td align="left">duration</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.10e+02</td>
<td align="right">2.22e+01</td>
<td align="right">37.0</td>
<td align="right">9.50e+01</td>
<td align="right">1.06e+02</td>
<td align="right">1.19e+02</td>
<td align="right">3.30e+02</td>
<td align="left">▃▇▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">gross</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.81e+07</td>
<td align="right">7.25e+07</td>
<td align="right">703.0</td>
<td align="right">1.23e+07</td>
<td align="right">3.47e+07</td>
<td align="right">7.56e+07</td>
<td align="right">7.61e+08</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">budget</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4.06e+07</td>
<td align="right">4.37e+07</td>
<td align="right">218.0</td>
<td align="right">1.10e+07</td>
<td align="right">2.60e+07</td>
<td align="right">5.50e+07</td>
<td align="right">3.00e+08</td>
<td align="left">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">cast_facebook_likes</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.24e+04</td>
<td align="right">2.05e+04</td>
<td align="right">0.0</td>
<td align="right">2.24e+03</td>
<td align="right">4.60e+03</td>
<td align="right">1.69e+04</td>
<td align="right">6.57e+05</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">votes</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.09e+05</td>
<td align="right">1.58e+05</td>
<td align="right">5.0</td>
<td align="right">1.99e+04</td>
<td align="right">5.57e+04</td>
<td align="right">1.33e+05</td>
<td align="right">1.69e+06</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">reviews</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5.03e+02</td>
<td align="right">4.94e+02</td>
<td align="right">2.0</td>
<td align="right">1.99e+02</td>
<td align="right">3.64e+02</td>
<td align="right">6.31e+02</td>
<td align="right">5.31e+03</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">rating</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">6.39e+00</td>
<td align="right">1.05e+00</td>
<td align="right">1.6</td>
<td align="right">5.80e+00</td>
<td align="right">6.50e+00</td>
<td align="right">7.10e+00</td>
<td align="right">9.30e+00</td>
<td align="left">▁▁▆▇▁</td>
</tr>
</tbody>
</table>
<p>Your R code and analysis should go here. If you want to insert a blank chunk of R code you can just hit <code>Ctrl/Cmd+Alt+I</code></p>
<pre class="r"><code>#Filter original data for two directors only, for t-test convenience

movies_rating1 &lt;- movies%&gt;%
  filter(director==c(&quot;Steven Spielberg&quot;))

movies_rating2 &lt;- movies%&gt;%
  filter(director==c(&quot;Tim Burton&quot;))

spielberg_burton &lt;- rbind(movies_rating1, movies_rating2)

# Have a look at the statistics of two director rating samples
mosaic::favstats(rating ~ director,data=spielberg_burton)</code></pre>
<pre><code>##           director min   Q1 median   Q3 max mean    sd  n missing
## 1 Steven Spielberg 6.2 7.20    7.6 8.00 8.9 7.57 0.695 23       0
## 2       Tim Burton 5.7 6.45    7.0 7.53 8.0 6.93 0.749 16       0</code></pre>
<pre class="r"><code># Run t-test
t.test(rating ~ director,data=spielberg_burton)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means between group Steven Spielberg and group Tim Burton is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<pre class="r"><code>#Filter original data for two directors only, for simulation 

movies_rating1 &lt;- movies %&gt;%
  filter(director == c(&quot;Steven Spielberg&quot;))

movies_rating2 &lt;- movies %&gt;%
  filter(director == c(&quot;Tim Burton&quot;))

spielberg_burton &lt;- rbind(movies_rating1, movies_rating2)

#Simulation
set.seed(1234)

ratings_in_null_world &lt;- spielberg_burton %&gt;%
  # Specify the variable of interest
  specify(rating ~ director) %&gt;%
  
  # Hypothesize a null of no (or zero) difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # Generate a bunch of simulated samples
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # Find the mean difference of each sample
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

# Calculate the p-value
ratings_in_null_world %&gt;%
  get_pvalue(obs_stat = 0.64, direction = &quot;both&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1   0.004</code></pre>
<pre class="r"><code>ratings_in_null_world %&gt;% visualize()</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-11-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><strong>Both t-test and simulation-based null distribution showed the null hypothesis should be rejected, implying there is a significant difference in IMDB rating for two directors</strong></p>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635~
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma~
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3~</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals . Hypothesis testing . Correlation analysis . Regression</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data = omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size,

df &lt;-
  mosaic::favstats (salary ~ gender, data = omega)[, c(&quot;gender&quot;, &quot;mean&quot;, &quot;sd&quot;, &quot;n&quot;)]
colnames(df) &lt;- c(&quot;gender&quot;, &quot;mean&quot;, &quot;SD&quot;, &quot;sample size&quot;)

# the t-critical value, the standard error, the margin of error,
df[, 5] &lt;- qt(0.95, df[, &quot;sample size&quot;] - 1, lower.tail = F)
df[, 6] &lt;- df[, &quot;SD&quot;] / sqrt(df[, &quot;sample size&quot;])
df[, 7] &lt;- 1.96 * df[, 6]
colnames(df)[5:7] &lt;- c(&quot;t-critical&quot;, &quot;SE&quot;, &quot;ME&quot;)
# and the low/high endpoints of a 95% condifence interval
df[, 8] &lt;- df[, &quot;mean&quot;] - df[, &quot;ME&quot;]
df[, 9] &lt;- df[, &quot;mean&quot;] + df[, &quot;ME&quot;]
colnames(df)[c(8, 9)] &lt;- c(&quot;low&quot;, &quot;high&quot;)

df</code></pre>
<pre><code>##   gender  mean   SD sample size t-critical   SE   ME   low  high
## 1 female 64543 7567          26      -1.71 1484 2909 61634 67452
## 2   male 73239 7463          24      -1.71 1523 2986 70253 76225</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>** We could see that the average salary by gender is different and male’s are higher than femails. However, the range of average mean of the salary between two gender is likely the same under 95% CI. Considering the relatively small sample size, their MEs are relatively big.</p>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code>#######

# hypothesis testing using t.test() 
t.test(salary~gender, data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package
set.seed(1234)
salary_in_Null &lt;- omega %&gt;% 
  specify(salary~gender)%&gt;%
  hypothesize(null = &quot;independence&quot;)%&gt;%
  generate(reps = 1000, type = &quot;permute&quot;)%&gt;%
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;female&quot;, &quot;male&quot;))

#get_pvalue(male = female,direction = &quot;both&quot;)
salary_in_Null</code></pre>
<pre><code>## Response: salary (numeric)
## Explanatory: gender (factor)
## Null Hypothesis: independence
## # A tibble: 1,000 x 2
##    replicate    stat
##        &lt;int&gt;   &lt;dbl&gt;
##  1         1  3031. 
##  2         2  2543. 
##  3         3  4998. 
##  4         4 -1085. 
##  5         5 -3498. 
##  6         6  -316. 
##  7         7 -5134. 
##  8         8 -1663. 
##  9         9   -43.3
## 10        10 -1349. 
## # ... with 990 more rows</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough
<em>The mean is significantly lower for women</em></p>
</blockquote>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 

df2 &lt;- mosaic::favstats (experience ~ gender, data=omega)[,c(&quot;gender&quot;,&quot;mean&quot;,&quot;sd&quot;,&quot;n&quot;)]
colnames(df2)&lt;-c(&quot;gender&quot;,&quot;mean&quot;,&quot;SD&quot;,&quot;sample size&quot;)

# the t-critical value, the standard error, the margin of error, 
df2[,5] &lt;- qt(0.95, df2[,&quot;sample size&quot;] - 1, lower.tail= F)
df2[,6] &lt;- df2[,&quot;SD&quot;]/sqrt(df2[,&quot;sample size&quot;])
df2[,7] &lt;- 1.96*df2[,6]
colnames(df2)[5:7] &lt;-c(&quot;t-critical&quot;,&quot;SE&quot;,&quot;ME&quot;)
# and the low/high endpoints of a 95% condifence interval
df2[,8] &lt;- df2[,&quot;mean&quot;]-df2[,&quot;ME&quot;]
df2[,9] &lt;- df2[,&quot;mean&quot;]+df2[,&quot;ME&quot;]
colnames(df2)[c(8,9)] &lt;- c(&quot;low&quot;,&quot;high&quot;)

df2</code></pre>
<pre><code>##   gender  mean    SD sample size t-critical   SE   ME   low high
## 1 female  7.38  8.51          26      -1.71 1.67 3.27  4.11 10.7
## 2   male 21.12 10.92          24      -1.71 2.23 4.37 16.76 25.5</code></pre>
<pre class="r"><code>t.test(experience~gender, data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<p>** There is a significant difference between the experience of the male and female executives. This conclusion validate the previous conclusion about the difference in male and female salaries that the differences might be attributable to the differences in experience**</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>omega%&gt;%
ggplot(aes(x = salary, y = experience))+
geom_point (aes(color = factor(gender)))+
geom_smooth(aes(color = factor(gender)))+
labs(title = &quot;Relationship Between Salary and Experience&quot;,
x = &quot;Salary&quot;,
y = &quot;Experience&quot;,
colour = &quot;Gender&quot;)</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-12-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
<p><strong>There is a positive relationship between salary and experience, and in average with same experience, male’s salary is relatively lower than female’s. However male’s scale of salary under the same working experience is larger than females. Hence, there might not have significant gender-based salary discrimination.</strong></p>
</div>
</div>
<div id="challenge-1-yield-curve-inversion" class="section level1">
<h1>Challenge 1: Yield Curve inversion</h1>
<p>Every so often, we hear warnings from commentators on the “inverted yield curve” and its predictive power with respect to recessions. An explainer what a <a href="https://www.reuters.com/article/us-usa-economy-yieldcurve-explainer/explainer-what-is-an-inverted-yield-curve-idUSKBN1O50GA">inverted yield curve is can be found here</a>. If you’d rather listen to something, here is a great podcast from <a href="https://www.podbean.com/media/share/dir-4zgj9-6aefd11">NPR on yield curve indicators</a></p>
<p>In addition, many articles and commentators think that, e.g., <a href="https://www.bloomberg.com/news/articles/2019-08-14/u-k-yield-curve-inverts-for-first-time-since-financial-crisis"><em>Yield curve inversion is viewed as a harbinger of recession</em></a>. One can always doubt whether inversions are truly a harbinger of recessions, and <a href="https://twitter.com/5_min_macro/status/1161627360946511873">use the attached parable on yield curve inversions</a>.</p>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/yield_curve_parable.jpg" width="100%" style="display: block; margin: auto;" /></p>
<p>In our case we will look at US data and use the <a href="https://fred.stlouisfed.org/">FRED database</a> to download historical yield curve rates, and plot the yield curves since 1999 to see when the yield curves flatten. If you want to know more, a very nice article that explains the <a href="https://fredblog.stlouisfed.org/2018/10/the-data-behind-the-fear-of-yield-curve-inversions/">yield curve is and its inversion can be found here</a>. At the end of this challenge you should produce this chart</p>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/yield_curve_challenge.png" width="100%" style="display: block; margin: auto;" /></p>
<p>First, we will load the yield curve data file that contains data on the yield curve since 1960-01-01</p>
<pre class="r"><code>yield_curve &lt;- read_csv(here::here(&quot;data&quot;, &quot;yield_curve.csv&quot;))

glimpse(yield_curve)</code></pre>
<pre><code>## Rows: 6,884
## Columns: 5
## $ date      &lt;date&gt; 1960-01-01, 1960-02-01, 1960-03-01, 1960-04-01, 1960-05-01,~
## $ series_id &lt;chr&gt; &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS~
## $ value     &lt;dbl&gt; 4.35, 3.96, 3.31, 3.23, 3.29, 2.46, 2.30, 2.30, 2.48, 2.30, ~
## $ maturity  &lt;chr&gt; &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, &quot;3m&quot;, ~
## $ duration  &lt;chr&gt; &quot;3-Month Treasury Bill&quot;, &quot;3-Month Treasury Bill&quot;, &quot;3-Month T~</code></pre>
<p>Our dataframe <code>yield_curve</code> has five columns (variables):</p>
<ul>
<li><code>date</code>: already a date object</li>
<li><code>series_id</code>: the FRED database ticker symbol</li>
<li><code>value</code>: the actual yield on that date</li>
<li><code>maturity</code>: a short hand for the maturity of the bond</li>
<li><code>duration</code>: the duration, written out in all its glory!</li>
</ul>
<div id="plotting-the-yield-curve" class="section level2">
<h2>Plotting the yield curve</h2>
<pre class="r"><code># get US recession dates after 1946 from Wikipedia 
# https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States

recessions &lt;- tibble(
  from = c(&quot;1948-11-01&quot;, &quot;1953-07-01&quot;, &quot;1957-08-01&quot;, &quot;1960-04-01&quot;, &quot;1969-12-01&quot;, &quot;1973-11-01&quot;, &quot;1980-01-01&quot;,&quot;1981-07-01&quot;, &quot;1990-07-01&quot;, &quot;2001-03-01&quot;, &quot;2007-12-01&quot;,&quot;2020-02-01&quot;),  
  to = c(&quot;1949-10-01&quot;, &quot;1954-05-01&quot;, &quot;1958-04-01&quot;, &quot;1961-02-01&quot;, &quot;1970-11-01&quot;, &quot;1975-03-01&quot;, &quot;1980-07-01&quot;, &quot;1982-11-01&quot;, &quot;1991-03-01&quot;, &quot;2001-11-01&quot;, &quot;2009-06-01&quot;, &quot;2020-04-30&quot;) 
  )  %&gt;% 
  mutate(From = ymd(from), 
         To=ymd(to),
         duration_days = To-From)


recessions</code></pre>
<pre><code>## # A tibble: 12 x 5
##    from       to         From       To         duration_days
##    &lt;chr&gt;      &lt;chr&gt;      &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;       
##  1 1948-11-01 1949-10-01 1948-11-01 1949-10-01 334 days     
##  2 1953-07-01 1954-05-01 1953-07-01 1954-05-01 304 days     
##  3 1957-08-01 1958-04-01 1957-08-01 1958-04-01 243 days     
##  4 1960-04-01 1961-02-01 1960-04-01 1961-02-01 306 days     
##  5 1969-12-01 1970-11-01 1969-12-01 1970-11-01 335 days     
##  6 1973-11-01 1975-03-01 1973-11-01 1975-03-01 485 days     
##  7 1980-01-01 1980-07-01 1980-01-01 1980-07-01 182 days     
##  8 1981-07-01 1982-11-01 1981-07-01 1982-11-01 488 days     
##  9 1990-07-01 1991-03-01 1990-07-01 1991-03-01 243 days     
## 10 2001-03-01 2001-11-01 2001-03-01 2001-11-01 245 days     
## 11 2007-12-01 2009-06-01 2007-12-01 2009-06-01 548 days     
## 12 2020-02-01 2020-04-30 2020-02-01 2020-04-30  89 days</code></pre>
<pre class="r"><code>recessions59up&lt;-filter(recessions,year(from)&gt;1959)</code></pre>
<pre class="r"><code>library(scales)
drop_na(yield_curve, maturity)</code></pre>
<pre><code>## # A tibble: 6,884 x 5
##    date       series_id value maturity duration             
##    &lt;date&gt;     &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;                
##  1 1960-01-01 TB3MS      4.35 3m       3-Month Treasury Bill
##  2 1960-02-01 TB3MS      3.96 3m       3-Month Treasury Bill
##  3 1960-03-01 TB3MS      3.31 3m       3-Month Treasury Bill
##  4 1960-04-01 TB3MS      3.23 3m       3-Month Treasury Bill
##  5 1960-05-01 TB3MS      3.29 3m       3-Month Treasury Bill
##  6 1960-06-01 TB3MS      2.46 3m       3-Month Treasury Bill
##  7 1960-07-01 TB3MS      2.3  3m       3-Month Treasury Bill
##  8 1960-08-01 TB3MS      2.3  3m       3-Month Treasury Bill
##  9 1960-09-01 TB3MS      2.48 3m       3-Month Treasury Bill
## 10 1960-10-01 TB3MS      2.3  3m       3-Month Treasury Bill
## # ... with 6,874 more rows</code></pre>
<pre class="r"><code>yield_10y &lt;-
  yield_curve %&gt;%
  filter(duration == &quot;10-Year Treasury Rate&quot;) %&gt;%
  summarise(Date = date,
            Value = value / 100,
            Maturity = maturity)

yield_3m &lt;-
  yield_curve %&gt;%
  filter(duration == &quot;3-Month Treasury Bill&quot;) %&gt;%
  summarise(Date = date,
            Value = value / 100,
            Maturity = maturity)

yield_3m10y &lt;-
  inner_join(yield_3m, yield_10y, by = &quot;Date&quot;) %&gt;%
  transmute(Date = Date, delta = (Value.y - Value.x))

ggplot() +
  geom_rect(
    data = recessions59up,
    aes(xmin = From, xmax = To),
    ymin = -Inf,
    ymax = Inf,
    alpha = 0.2
  ) +
  geom_line(data = yield_3m10y, aes(x = Date, y = delta * 100)) +
  geom_area(data = yield_3m10y,
            color = &quot;#5DADE2&quot;,
            aes(x = (Date), y = ifelse(delta &lt; 0, delta * 100, 0)),
            fill =
              &quot;#F5B7B1&quot;) +
  geom_area(data = yield_3m10y,
            color = &quot;#7FB3D5&quot;,
            aes(x = (Date), y = ifelse(delta &gt; 0, delta * 100, 0)),
            fill =
              &quot;#AED6F1&quot;) +
  theme_bw() +
  labs(
    x = &quot;&quot;,
    y = &quot;Difference (10 year-3 month) yield in %&quot;,
    caption = &quot;Source: St.Louis Federal Reserve Economic Database (FRED)&quot;,
    title = &quot;Yield Curve inversion: 10-year minus 3-month U.S. Treasury rates&quot;,
    subtitle = &quot;Difference in % points monthly averages.\nShaded area corresponds to recessions&quot;
  ) +
  theme(plot.title = element_text(face = &quot;bold&quot;))+
  scale_x_date(date_breaks = &quot;2 years&quot;, labels = date_format(&quot;%Y&quot;), limits = c(as.Date(&quot;1960-12-01&quot;), as.Date(&quot;2021-01-01&quot;)))</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-13-1.png" width="1440" style="display: block; margin: auto;" /></p>
<p>This may seem long but it should be easy to produce the following three plots</p>
<div id="yields-on-us-rates-by-duration-since-1960" class="section level3">
<h3>Yields on US rates by duration since 1960</h3>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/yield_curve1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>lev &lt;- c(&quot;3m&quot;, &quot;6m&quot;, &quot;1y&quot;, &quot;2y&quot;, &quot;3y&quot;, &quot;5y&quot;, &quot;7y&quot;, &quot;10y&quot;, &quot;20y&quot;)


lev_duration &lt;- c(
  &quot;3-Month Treasury Bill&quot;,
  &quot;6-Month Treasury Bill&quot;,
  &quot;1-Year Treasury Rate&quot;,
  &quot;2-Year Treasury Rate&quot;,
  &quot;3-Year Treasury Rate&quot;,
  &quot;5-Year Treasury Rate&quot;,
  &quot;7-Year Treasury Rate&quot;,
  &quot;10-Year Treasury Rate&quot;,
  &quot;20-Year Treasury Rate&quot;,
  &quot;30-Year Treasury Rate&quot;
)

yield_curve_new &lt;- arrange(transform(yield_curve,
                                     duration = factor(duration, levels = lev_duration)), duration)

yield_curve_new %&gt;%
  #mutate(maturity=factor(maturity,order=TRUE,levels=lev))%&gt;%
  #arrange(date,maturity)%&gt;%
  ggplot(aes(x = date, y = value, colour = duration)) +
  geom_line() +
  facet_wrap( ~ duration, nrow = 5) +
  theme_bw() +
  labs(
    title = &quot;Yields on U.S. Treasury rates since 1960&quot;,
    x = &quot;&quot;,
    y = &quot;%&quot;,
    caption = &quot;Source: St.Louis Federal Reserve Economic Database (FRED)&quot;
  ) +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-14-1.png" width="1440" style="display: block; margin: auto;" /></p>
</div>
<div id="monthly-yields-on-us-rates-by-duration-since-1999-on-a-year-by-year-basis" class="section level3">
<h3>Monthly yields on US rates by duration since 1999 on a year-by-year basis</h3>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/yield_curve2.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(lubridate)

lev &lt;-
  c(&quot;3m&quot;, &quot;6m&quot;, &quot;1y&quot;, &quot;2y&quot;, &quot;3y&quot;, &quot;5y&quot;, &quot;7y&quot;, &quot;10y&quot;, &quot;20y&quot;, &quot;30y&quot;)

yield_curve_new2 &lt;- arrange(transform(yield_curve,
                                      maturity = factor(maturity, levels = lev)), maturity)

yield_curve_new2 &lt;-
  yield_curve_new2 %&gt;%
  mutate(yield_curve_new2,
         Month = month(date),
         Year = year(date)) %&gt;%
  arrange(Month, Year, maturity) %&gt;%
  mutate(count = 1:length(Month))



yield_curve_new2&lt;-drop_na(yield_curve_new2)


yield_curve_new2 %&gt;%
  filter(Year &gt;= 1999) %&gt;%
  ggplot(aes(
    x = maturity,
    y = value,
    color = as.factor(Year),
    group = Month
  )) +
  geom_line() +
  facet_wrap(~ year(date), nrow = 6) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;) +
  labs(
    x = &quot;Maturity&quot;,
    y = &quot;Yield (%)&quot;,
    title = &quot;US Yield Curve&quot;,
    caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;
  )</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-15-1.png" width="1248" style="display: block; margin: auto;" /></p>
</div>
<div id="month-and-10-year-yields-since-1999" class="section level3">
<h3>3-month and 10-year yields since 1999</h3>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/yield_curve3.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>yield_3mAND10y &lt;-
  inner_join(yield_3m, yield_10y, by = &quot;Date&quot;) %&gt;%
  filter(year(Date) &gt;= 1999) %&gt;%
  mutate(Value.x = Value.x * 100, Value.y = Value.y * 100)

#lgnd&lt;-c(&quot;a&quot;,&quot;b&quot;)

#yield_3mAND10y%&gt;%
#ggplot(aes(x=Date))+
#  geom_line(aes(y=Value.x,colour=&quot;#A2D9CE&quot;,color=&quot;a&quot;))+
#  geom_line(aes(y=Value.y,colour=&quot;#F1948A&quot;,color=&quot;b&quot;))+
# theme_bw()+
#   labs(
#    title = &quot;Yields on 3 months and 10 years U.S. treasury since 1999&quot;,
#    x = &quot;&quot;,
#    y = &quot;%&quot;,
#   caption=&quot;Source: St.Louis Federal Reserve Economic Database (FRED)&quot;,
#   color=&quot;Legend&quot;)



names(yield_3mAND10y)[c(2, 4)] = c(&quot;3-Month Treasury Bill&quot;, &quot;10-Year Treasury Rate&quot;)
cols &lt;- c(&quot;#A2D9CE&quot;, &quot;#F1948A&quot;)

yield_3mAND10y %&gt;%
  gather(key = measure,
         value = Rate,
         c(&quot;3-Month Treasury Bill&quot;, &quot;10-Year Treasury Rate&quot;)) %&gt;%
  ggplot(aes(
    x = Date,
    y = Rate,
    group = measure,
    colour = measure
  )) +
  geom_line(fill = cols) +
  theme_bw() +
  labs(
    title = &quot;Yields on 3 months and 10 years U.S. treasury since 1999&quot;,
    x = &quot;&quot;,
    y = &quot;%&quot;,
    caption = &quot;Source: St.Louis Federal Reserve Economic Database (FRED)&quot;,
    color = &quot;&quot;
  ) +
  scale_color_manual(values = cols)</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-16-1.png" width="1248" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="challenge-2-gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2: GDP components over time and among countries</h1>
<p>At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">Wikipedia GDP page</a>.</p>
<p>The GDP data we will look at is from the <a href="https://unstats.un.org/unsd/snaama/Downloads">United Nations’ National Accounts Main Aggregates Database</a>, which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country’s GDP. The file we will work with is <a href="http://unstats.un.org/unsd/amaapi/api/file/6">GDP and its breakdown at constant 2010 prices in US Dollars</a> and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised</p>
<pre class="r"><code>UN_GDP_data  &lt;-
  read_excel(
    here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xlsx&quot;),
    # Excel filename
    sheet = &quot;Download-GDPconstant-USD-countr&quot;,
    # Sheet name
    skip = 2
  ) # Number of rows to skip</code></pre>
<p>The first thing you need to do is to tidy the data, as it is in wide format and you must make it into long, tidy format. Please express all figures in billions (divide values by <code>1e9</code>, or <span class="math inline">\(10^9\)</span>), and you want to rename the indicators into something shorter.</p>
<pre class="r"><code>tidy_GDP_data  &lt;- UN_GDP_data %&gt;%
  #change wider to longer by year
  pivot_longer(cols = c(4:51),
               names_to = &quot;year&quot;,
               values_to = &quot;value_e&quot;) %&gt;%
  #into billions
  mutate(value = value_e / 1e9)

glimpse(tidy_GDP_data)</code></pre>
<pre><code>## Rows: 176,976
## Columns: 8
## $ CountryID     &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,~
## $ Country       &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanista~
## $ IndicatorName &lt;chr&gt; &quot;Final consumption expenditure&quot;, &quot;Final consumption expe~
## $ `2018`        &lt;dbl&gt; 2.13e+10, 2.13e+10, 2.13e+10, 2.13e+10, 2.13e+10, 2.13e+~
## $ `2019`        &lt;dbl&gt; 2.46e+10, 2.46e+10, 2.46e+10, 2.46e+10, 2.46e+10, 2.46e+~
## $ year          &lt;chr&gt; &quot;1970&quot;, &quot;1971&quot;, &quot;1972&quot;, &quot;1973&quot;, &quot;1974&quot;, &quot;1975&quot;, &quot;1976&quot;, ~
## $ value_e       &lt;dbl&gt; 3.07e+09, 2.96e+09, 2.89e+09, 3.10e+09, 3.33e+09, 3.51e+~
## $ value         &lt;dbl&gt; 3.07, 2.96, 2.89, 3.10, 3.33, 3.51, 3.59, 3.83, 3.99, 3.~</code></pre>
<pre class="r"><code># Let us compare GDP components for these 3 countries
country_list &lt;- c(&quot;United States&quot;, &quot;India&quot;, &quot;Germany&quot;)</code></pre>
<p>First, can you produce this plot?</p>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/gdp1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#create list of needed components
component_list &lt;-
  c(
    &quot;Gross capital formation&quot;,
    &quot;Exports of goods and services&quot;,
    &quot;General government final consumption expenditure&quot;,
    &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
    &quot;Imports of goods and services&quot;
  )

needed_GDP_data &lt;- tidy_GDP_data %&gt;%
  #get needed data filtered by country and components
  filter(Country %in% country_list) %&gt;%
  filter(IndicatorName %in% component_list) %&gt;%
  #turn `IndicatorName` from character to a factor variable
  mutate(indicator = factor(
    IndicatorName,
    levels = c(
      &quot;Gross capital formation&quot;,
      &quot;Exports of goods and services&quot;,
      &quot;General government final consumption expenditure&quot;,
      &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
      &quot;Imports of goods and services&quot;
    ),
    labels = c(
      &quot;Gross capital formation&quot;,
      &quot;Exports&quot;,
      &quot;Government expenditure&quot;,
      &quot;Household expenditure&quot;,
      &quot;Imports&quot;
    )
  )) %&gt;%
  #change &quot;year&quot; into numerical
  mutate(year_n = as.numeric(year))


#make plot
needed_GDP_data %&gt;%
  ggplot(aes(x = year_n, y = value, colour = indicator)) +
  geom_line(size = .8) +
  facet_wrap( ~ Country, nrow = 1) +
  theme_bw() +
  labs(
    title = &quot;GDP components over time&quot;,
    subtitle = &quot;In constant 2010 USD&quot;,
    x = &quot;&quot;,
    y = &quot;Billion US$&quot;,
    color = &quot;Components of GDP&quot;
  ) +
  scale_x_continuous(breaks = seq(1970, 2017, 10))</code></pre>
<p><img src="homework3_G11_v3%20(1)_files/figure-html/unnamed-chunk-17-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<pre class="r"><code>#change longer to wider
needed_GDP_data &lt;- needed_GDP_data[, c(2, 6, 7, 8,9,10)] %&gt;%
  pivot_wider(names_from = &quot;indicator&quot;, values_from = &quot;value&quot;)
#calculate net exports
needed_GDP_data &lt;- needed_GDP_data %&gt;%
  mutate(net_exports = Exports - Imports)
#generate GDP
needed_GDP_data$GDP &lt;- rowSums(needed_GDP_data[, c(3, 4, 5, 8)])

#calculate proportion for each component
needed_GDP_data &lt;- needed_GDP_data %&gt;%
  mutate(
    G_ratio = `Government expenditure` / GDP,
    C_ratio = `Household expenditure` / GDP,
    I_ratio = `Gross capital formation` / GDP,
    net_exports_ratio = net_exports / GDP
  )</code></pre>
<blockquote>
<p>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</p>
</blockquote>
<pre class="r"><code>#get the GDP figure included in the dataframe
gdp_origin &lt;- tidy_GDP_data[, c(2, 3, 4, 6)] %&gt;%
  filter(IndicatorName == &quot;Gross Domestic Product (GDP)&quot;) %&gt;%
  filter(Country %in% country_list) %&gt;%
  mutate(year_n = as.numeric(year),
         compare_name = paste(Country, year_n))

#create a new variable to make it easier to join two data
needed_GDP_data &lt;- needed_GDP_data %&gt;%
  mutate(compare_name = paste(Country, year_n))

#join our gdp and origin gdp
#mydata_compare &lt;-
 # left_join(gdp_origin, needed_GDP_data, by = &quot;compare_name&quot;) %&gt;%
  #calculate difference
  #mutate(difference_gdp = (GDP - value) / value * 100)

#create a new dataset to see clearly
#only data needed
#show_difference &lt;- mydata_compare[, c(1, 3, 4, 14, 20)]
#change variable name
#names(show_difference)[3:4] &lt;- c(&quot;origin_GDP&quot;, &quot;calculated_GDP&quot;)

#show_difference</code></pre>
<p><strong>We notice from dataset ‘show_difference’ that, for Germany and US, the GDP we calculated is always larger than GDP initially included.</strong></p>
<p><img src="C:/Users/taxel/OneDrive/Desktop/my_website/images/gdp2.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#we try to reproduce the plot use &#39;needed_GDP_data&#39;
#needed_GDP_data_plot  &lt;- needed_GDP_data %&gt;%
  #change wider to longer by indicator, easier to plot
 # pivot_longer(cols = c(10:13),
             #  names_to = &quot;indicator&quot;,
              # values_to = &quot;proportion&quot;)

#change the name of legend
#needed_GDP_data_plot$indicator &lt;-
 # factor(
  #  needed_GDP_data_plot$indicator,
   # levels = c(&#39;G_ratio&#39;, &#39;C_ratio&#39;, &#39;I_ratio&#39;, &quot;net_exports_ratio&quot;),
    #labels = c(
  #    &quot;Government expenditure&quot;,
   #   &quot;Household expenditure&quot;,
    #  &quot;Gross capital formation&quot;,
     # &quot;Net exports&quot;
 #   )
  #)

#make plot, as we did above
#needed_GDP_data_plot %&gt;%
 # ggplot(aes(x = year_n, y = proportion, color = indicator)) +
  #geom_line(size = .8) +
  #scale_color_manual(
   # values = c(
  #    &quot;Government expenditure&quot; = &quot;#F8766D&quot;,
   #   &quot;Gross capital formation&quot; = &quot;#7CAE00&quot;,
    #  &quot;Household expenditure&quot; = &quot;#00BFC4&quot;,
     # &quot;Net exports&quot; = &quot;#C77CFF&quot;
    #)
  #) +
  #facet_wrap( ~ Country, nrow = 1) +
  #theme_bw() +
  #labs(
   # title = &quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;,
    #x = &quot;&quot;,
    #y = &quot;proportion&quot;,
  #  caption = &quot;Source:United Nations, https://unstats.un.org/unsd/snaama/Downloads&quot;,
   # color = &quot;&quot;
#  ) +
 # scale_x_continuous(breaks = seq(1970, 2017, 10)) +
  #scale_y_continuous(labels = scales::percent)</code></pre>
<blockquote>
<p>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</p>
</blockquote>
<p><strong>For these three countries, household consumption is the largest element of expenditure across the economy, and we think it is also an important indicator of a country’s economy landscape. As a country develops, the proportion of household expenditure, which is the expense of people’s daily basic need, will go down, and other proportion will increase. This is pretty much like the Engel’s law. For India, the proportion of household expenditure is the highest among three, which shows it is still a developing country. However, with the fast speed it developed during the late 20th century, this proportion went down and capital formation increased. A negative net exports shows that it imports a greater value than it exports, it has a trade deficit. For developed countries Germany and US, their graphs are somehow alike. However, Germany’s net exports increased a lot since 21th century, which means Germany’s goods are so competitive. We believe it is because reputation for quality precision engineering gives them a competitive advantage in selling goods to foreign countries, as well as the relatively weak euro.</strong></p>
<blockquote>
<p>If you want to, please change <code>country_list &lt;- c("United States","India", "Germany")</code> to include your own country and compare it with any two other countries you like</p>
</blockquote>
</div>
<div id="deliverables" class="section level1">
<h1>Deliverables</h1>
<p>There is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Knit the edited and completed R Markdown file as an HTML document (use the “Knit” button at the top of the script editor window) and upload it to Canvas.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: B11</li>
<li>Approximately how much time did you spend on this problem set: 1d</li>
<li>What, if anything, gave you the most trouble: NA</li>
</ul>
<p><strong>Please seek out help when you need it,</strong> and remember the <a href="https://mfa2022.netlify.app/syllabus/#the-15-minute-rule" target="_blank">15-minute rule</a>. You know enough R (and have enough examples of code from class and your readings) to be able to do this. If you get stuck, ask for help from others, post a question on Slack– and remember that I am here to help too!</p>
<blockquote>
<p>As a true test to yourself, do you understand the code you submitted and are you able to explain it to someone else?</p>
</blockquote>
</div>
<div id="rubric" class="section level1">
<h1>Rubric</h1>
<p>Check minus (1/5): Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analyzed.</p>
<p>Check (3/5): Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output).</p>
<p>Check plus (5/5): Finished all components of the assignment correctly and addressed both challenges. Code is well-documented (both self-documented and with additional comments as necessary). Used tidyverse, instead of base R. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or you’ve written additional text to describe how you interpret the output.</p>
</div>
